name: Manually build and deploy site

on:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * 1-5" # 06:05am Monday-Friday
      timezone: "America/Los_Angeles"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"

      - name: Netlify manual deploy
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --build --context production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
